"""Seed a small, clearly-labelled demonstration dataset.

Why this exists: the archive ships `data/paimana.db` empty (no tables at all),
and the `scripts/ingest_reports.py` referenced by `data/README.md` is not
present, so there is no way to start the application with data. This script
produces just enough to exercise every code path end to end.

Everything it writes is flagged `is_demo=True` and attributed to a source
document named so that it cannot be mistaken for a real Flash Report. It is a
development fixture, not a substitute for ingestion.

    python scripts/dev_seed.py             # seed if empty
    python scripts/dev_seed.py --reset     # wipe demo rows and reseed
"""
from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "backend"))

from app.db import SessionLocal, init_db  # noqa: E402
from app.models import (  # noqa: E402
    DataOrigin,
    DataSource,
    ExtractedRecord,
    Project,
    ProjectSnapshot,
    User,
    UserRole,
)
from app.security import hash_password  # noqa: E402
from app.services import risk_engine  # noqa: E402
from app.services.warnings import generate_all_alerts  # noqa: E402

PERIODS = ["2026-04", "2026-05", "2026-06", "2026-07"]

SECTORS = ["Railways", "Road Transport & Highways", "Petroleum & Natural Gas",
           "Power", "Urban Development", "Water Resources", "Civil Aviation",
           "Coal", "Shipping & Ports", "Telecommunications"]

STATES = ["Bihar", "Maharashtra", "Uttar Pradesh", "Karnataka", "Gujarat",
          "Tamil Nadu", "West Bengal", "Rajasthan", "Odisha", "Madhya Pradesh",
          "Andhra Pradesh", "Kerala"]

NAME_PARTS = [
    ("Doubling of", "Railway Line"), ("Four Laning of", "Highway Section"),
    ("Construction of", "Bypass"), ("Development of", "Terminal"),
    ("Augmentation of", "Water Supply Scheme"), ("Modernisation of", "Power Station"),
    ("Electrification of", "Section"), ("Expansion of", "Port Facility"),
    ("New", "Metro Corridor"), ("Rehabilitation of", "Canal System"),
]

PLACES = ["Araria", "Bhagalpur", "Nashik", "Kanpur", "Hubli", "Surat", "Madurai",
          "Asansol", "Kota", "Cuttack", "Indore", "Guntur", "Kochi", "Raipur",
          "Jhansi", "Solapur", "Rourkela", "Vellore", "Ajmer", "Siliguri"]


#: Correlated health profiles. The risk engine weights cost escalation (25),
#: schedule delay (25), progress divergence (20), progress stall (15) and the
#: time-vs-progress gap (15). Seeding these independently at random produces a
#: narrow band of MODERATE scores and no HIGH or SEVERE projects at all, which
#: leaves the most important query paths untested. Each profile below moves the
#: drivers together, the way a genuinely troubled project does.
PROFILES = [
    # name,        weight, escalation %,   delay months, monthly progress, elapsed %
    ("healthy",    0.42, (0.0, 3.0),      (0, 2),       (1.8, 3.5),       (25, 80)),
    ("watch",      0.28, (5.0, 22.0),     (3, 14),      (0.8, 2.0),       (60, 100)),
    ("distressed", 0.20, (25.0, 55.0),    (16, 40),     (0.2, 0.9),       (95, 135)),
    ("critical",   0.10, (60.0, 140.0),   (44, 96),     (0.0, 0.25),      (130, 210)),
]


def pick_profile(rng):
    roll = rng.random()
    cumulative = 0.0
    for profile in PROFILES:
        cumulative += profile[1]
        if roll <= cumulative:
            return profile
    return PROFILES[-1]


def build(session, count: int = 90) -> None:
    rng = random.Random(20260903)

    sources = {}
    for index, period in enumerate(PERIODS):
        label = dt.date(int(period[:4]), int(period[5:]), 1).strftime("%B %Y").upper()
        filename = f"DEMO_SeedData_{period}.synthetic"
        source = DataSource(
            filename=filename,
            sha256=hashlib.sha256(filename.encode()).hexdigest(),
            document_type="DEMO_SEED",
            report_period=period,
            report_label=label,
            issue_number=f"DEMO-{index + 1}",
            page_count=6 + (count if False else 40),
            publisher="PAIMANA development seed — NOT a published Flash Report",
            is_demo=True,
            notes="Generated by scripts/dev_seed.py for local development and testing.",
        )
        session.add(source)
        sources[period] = source
    session.flush()

    for i in range(count):
        prefix, suffix = rng.choice(NAME_PARTS)
        place = rng.choice(PLACES)
        name = f"{prefix} {place} {suffix}"
        code = str(100000 + i * 7)

        profile_name, _w, esc_range, delay_range, step_range, elapsed_range = pick_profile(rng)

        project = Project(
            project_code=code,
            name=name,
            agency=f"{rng.choice(['National', 'Central', 'State'])} "
                   f"{rng.choice(['Development', 'Infrastructure', 'Works'])} Authority",
            ministry=rng.choice(SECTORS),
            sector=rng.choice(SECTORS),
            state=rng.choice(STATES),
            sector_origin=DataOrigin.DEMO,
            state_origin=DataOrigin.DEMO,
            is_demo=True,
            first_seen_period=PERIODS[0],
            last_seen_period=PERIODS[-1],
        )
        session.add(project)
        session.flush()

        original = round(rng.uniform(120, 9000), 2)
        escalation = round(rng.uniform(*esc_range), 2)
        revised = round(original * (1 + escalation / 100), 2)
        delay = rng.randint(*delay_range)
        elapsed = round(rng.uniform(*elapsed_range), 1)

        # A troubled project is further behind, so start it lower.
        base_progress = {
            "healthy": rng.uniform(35, 92), "watch": rng.uniform(20, 70),
            "distressed": rng.uniform(8, 45), "critical": rng.uniform(2, 28),
        }[profile_name]

        approval = dt.date(2019 + rng.randint(0, 4), rng.randint(1, 12), 1)
        original_completion = approval + dt.timedelta(days=rng.randint(700, 2600))

        # Financial progress running ahead of physical is the divergence signal:
        # money spent faster than work delivered.
        divergence_bias = {
            "healthy": rng.uniform(-4, 4), "watch": rng.uniform(2, 14),
            "distressed": rng.uniform(10, 30), "critical": rng.uniform(22, 48),
        }[profile_name]

        page_number = 6 + (i // 12)

        for step, period in enumerate(PERIODS):
            physical = round(min(99.9, base_progress + step * rng.uniform(*step_range)), 1)
            financial = round(max(0.0, min(160.0, physical + divergence_bias)), 1)
            expenditure = round(revised * financial / 100, 2)

            # Real ingestion writes an ExtractedRecord per row and links the
            # snapshot to it, which is what makes provenance traceable to a page.
            # The seed does the same so the provenance API and its test behave
            # exactly as they would against ingested data.
            record = ExtractedRecord(
                source_id=sources[period].id,
                page_number=page_number,
                table_name="DEMO SEED TABLE",
                row_index=i,
                raw_payload={
                    "Project": name,
                    "Physical Progress": f"{physical}",
                    "Original Cost": f"{original}",
                    "Revised Cost": f"{revised}",
                },
                normalised_payload={
                    "physical_progress": physical,
                    "original_cost": original,
                    "revised_cost": revised,
                },
                extraction_confidence=0.95,
                field_confidence={"physical_progress": 0.95, "original_cost": 0.95},
                parse_warnings=[],
            )
            session.add(record)
            session.flush()

            snapshot = ProjectSnapshot(
                project_id=project.id,
                source_id=sources[period].id,
                record_id=record.id,
                report_period=period,
                original_cost=original,
                revised_cost=revised,
                expenditure=expenditure,
                physical_progress=physical,
                financial_progress=financial,
                approval_date=approval,
                start_date=approval + dt.timedelta(days=90),
                original_completion=original_completion,
                revised_completion=original_completion + dt.timedelta(days=delay * 30),
                cost_escalation_pct=escalation,
                progress_divergence=round(financial - physical, 2),
                schedule_delay_months=delay,
                elapsed_time_pct=elapsed,
                data_quality_status="OK",
                completeness=round(rng.uniform(0.72, 1.0), 2),
                is_demo=True,
            )
            session.add(snapshot)

    session.commit()


def seed_users(session) -> None:
    accounts = [
        ("admin", "paimana-admin", "Demo Administrator", UserRole.ADMIN),
        ("analyst", "paimana-analyst", "Demo Analyst", UserRole.ANALYST),
        ("viewer", "paimana-viewer", "Demo Viewer", UserRole.VIEWER),
    ]
    for username, password, full_name, role in accounts:
        if session.query(User).filter_by(username=username).one_or_none():
            continue
        session.add(User(
            username=username, full_name=full_name, designation="Development account",
            password_hash=hash_password(password), role=role, is_active=True,
        ))
    session.commit()


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reset", action="store_true", help="delete demo rows first")
    parser.add_argument("--count", type=int, default=90, help="number of demo projects")
    args = parser.parse_args()

    init_db()
    session = SessionLocal()
    try:
        if args.reset:
            # Order matters: alerts and risk events reference snapshots, and
            # SQLite enforces the foreign keys (PRAGMA foreign_keys=ON in db.py).
            from app.models import Alert, DataQualityIssue, Intervention, RiskEvent

            demo_ids = [p.id for p in session.query(Project).filter_by(is_demo=True).all()]
            if demo_ids:
                for model in (Intervention, Alert, RiskEvent, DataQualityIssue):
                    session.query(model).filter(model.project_id.in_(demo_ids)).delete(
                        synchronize_session=False
                    )
                session.commit()
            session.query(ProjectSnapshot).filter_by(is_demo=True).delete(
                synchronize_session=False
            )
            demo_source_ids = [
                s_.id for s_ in session.query(DataSource).filter_by(is_demo=True).all()
            ]
            if demo_source_ids:
                session.query(ExtractedRecord).filter(
                    ExtractedRecord.source_id.in_(demo_source_ids)
                ).delete(synchronize_session=False)
            session.query(Project).filter_by(is_demo=True).delete(synchronize_session=False)
            session.query(DataSource).filter_by(is_demo=True).delete(
                synchronize_session=False
            )
            session.commit()

        if session.query(Project).count():
            print("Projects already present. Use --reset to rebuild the demo data.")
            return

        print(f"Seeding {args.count} demonstration projects across {len(PERIODS)} periods…")
        build(session, args.count)
        seed_users(session)

        print("Scoring risk…")
        risk_engine.recalculate_all(session)
        print("Generating early warnings…")
        generate_all_alerts(session)

        print(
            f"Done. {session.query(Project).count()} projects, "
            f"{session.query(ProjectSnapshot).count()} snapshots. "
            "All rows are flagged is_demo=True."
        )
    finally:
        session.close()


if __name__ == "__main__":
    main()
